### ISSUE TITLE
Add the possibility to change the primary key type

### ISSUE THREAD

**Issue by lnu** [nhibernate/NHibernate.AspNet.Identity#26]
This is the only missing part of the EF provider. What do you think?

**Comment by titobf** [comment]
+1

**Comment by lnu** [comment]
@milesibastos I saw you started something. I also did some changes last week. It's almost working but some tests are failing. You can check it [here](https://github.com/lnu/NHibernate.AspNet.Identity/tree/GenericId).
I faced an issue with the NHibernate Linq provider(same as [here](http://stackoverflow.com/questions/25229048/generic-repository-and-custom-type-of-entity-id)).
