### ISSUE TITLE
Update Quick-Start guide

### ISSUE THREAD

**Issue by DerekJarvis** [nhibernate/NHibernate.AspNet.Identity#29]
I'm trying to implement AspNet.Identity in my WebAPI2 application which uses NHibernate as the ORM. I think this project is a great step in the right direction for me.

I created a Web project, followed the quick-start guide, and I was left with some errors and warnings. I've created a Wiki page that has the additional steps I've had to follow to remove the errors and warnings. One of which, I'm not quite sure how to fix. Please advise if I'm going in the completely wrong direction :smile:.

https://github.com/milesibastos/NHibernate.AspNet.Identity/wiki/Quick-Start-Updates

**Comment by x86digital** [comment]
Did you end up getting this fixed?

**Comment by lnu** [comment]
Don't hesitate to create a pull request to improve the quick start.
