### ISSUE TITLE
Move to NHibernate organization?

### ISSUE THREAD

**Issue by hazzik** [nhibernate/NHibernate.AspNet.Identity#37]
I mean here: https://github.com/nhibernate

**Comment by milesibastos** [comment]
course we can!
I automate the build and deploy to the nuget with appveyor.
We will need to point to the new fork.

**Comment by lnu** [comment]
Good news :)

**Comment by hazzik** [comment]
Ok, great.

Now you should be able to **transfer** the repository using settings page https://github.com/milesibastos/NHibernate.AspNet.Identity/settings

![step1](https://cloud.githubusercontent.com/assets/144791/6789271/fc7a2444-d203-11e4-84a3-d98402916440.png)

![step2](https://cloud.githubusercontent.com/assets/144791/6789259/e15d0c44-d203-11e4-91a1-1ff26a1f1637.png)

**Comment by milesibastos** [comment]
Done!
