### ISSUE TITLE
Unable to access properties from AspNetUsers table

### ISSUE THREAD

**Issue by ewhitmore** [nhibernate/NHibernate.AspNet.Identity#40]
Code: 
    UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(session));

The only properties i have access to are "MyProperty".  I can't access Id, Email, username, etc.  Is there a way around this without hitting the tables directly through nhibernate?

**Comment by lnu** [comment]
for anyone interested check https://github.com/lnu/NHibernateIdentity
