### ISSUE TITLE
Quick Start

### ISSUE THREAD

**Issue by x86digital** [nhibernate/NHibernate.AspNet.Identity#42]
I'm trying to get this into my project but the 3 step quick start doesn't seem to work? Is there an example solution of this already implemented? Any help please.

**Comment by lnu** [comment]
Is this [sample](https://github.com/lnu/NHibernateIdentity) enough for you?

**Comment by adaam2** [comment]
+1 The quick start guide doesn't seem to account for OWIN based implementations. Can we get an update please?

Cheers

**Comment by HenryHatten** [comment]
The sample mentioned above does not seem to work. After getting it to run by downloading a missing db file from an earlier version, any user accounts registered are not stored in the database, and trying to logoff and login again does not work.

**Comment by lnu** [comment]
https://github.com/lnu/NHibernateIdentity/issues/1

**Comment by lnu** [comment]
https://github.com/lnu/NHibernateIdentity/issues/1

**Comment by HenryHatten** [comment]
Yes that works fine, thanks!
