### ISSUE TITLE
Use with the last Sharp Architecture

### ISSUE THREAD

**Issue by deromero** [nhibernate/NHibernate.AspNet.Identity#43]
I've used this assembly with Sharp Architecture before without problems.
But now I have some Issues. 

The first that I resolved was the implementation in Castle Windsor installer of ISession.
But now and it is the issue with the highest priority: 
I can't make work the automapping of Sharp. 
I've completed the steps with the older versions but the mappings for Nhibernate.Aspnet.Identity does not appears on the solution. 
When I use the userstore for a Query.. (login, register, etc) I got this error

Interceptor.OnPrepareStatement(SqlString) returned null or empty SqlString.

This means that the entities on the assembly are no mapped. 

Please can you give an advice about this. 

Thanks

**Comment by nforss** [comment]
I have the same problem. deromero: Did you find a solution?

**Comment by lnu** [comment]
As I understand, it was working? When did it stop, with which release?

**Comment by lnu** [comment]
I think we can officially close it.
