### ISSUE TITLE
`IdentityUser` is not generic.

### ISSUE THREAD

**Issue by bradykelly** [nhibernate/NHibernate.AspNet.Identity#46]
I am used to the EF Identity setup, where `IdentityUser` is generic, so I can declare `ApplicationUser: IdentityUser<int....`, but now replacing the EF Identity with your NHIbernate Identity has replaced the generic `IdentityUser` with one that has `string` hard coded as the key. How do I use an `int` key?

**Comment by lnu** [comment]
It's not possible now. Sorry.
There are some development going on about this but it's not yet ready.

**Comment by bradykelly** [comment]
Thanks. I'll have to do my own now, but will check back later.

**Comment by hazzik** [comment]
@bradykelly you are more than wellcome to contribute your version.

**Comment by bradykelly** [comment]
Thank you, but I am a rank beginner at NHibernate, but maybe some reviewing could help me contribute.

**Comment by lnu** [comment]
I have something but my main issue is to provide the mapping part with the `MappingHelper`. I'll try to commit what I have now and see what we can do.

**Comment by lnu** [comment]
#26
