### ISSUE TITLE
Any way to change the User ID from a GUID to int?

### ISSUE THREAD

**Issue by HenryHatten** [nhibernate/NHibernate.AspNet.Identity#49]
I'd like to change the User ID in NHibernate.AspNet.Identity.IdentityUser from a string (GUID) to an Int32.

There's some info about this for the normal Asp.Net identity stuff but it doesn't seem to be applicable here. Is this possible at all? What's the best way to go about it?

**Comment by lnu** [comment]
Related to https://github.com/nhibernate/NHibernate.AspNet.Identity/issues/46
It's not supported yet.

**Comment by sunnyokoro** [comment]
I have been able to change the UserID to integers but unable to commit due to permission issues.
How do I commit my changes to the repo?

**Comment by sunnyokoro** [comment]
I have been able to change the UserID to integers but unable to commit due
to permission issues.
How do I commit my changes to the repo?





Yours
Sunday Okoro Awa
<http://about.me/sunny.okoro?promo=email_sig>Kno
*Know more about me*  about.me/sunny.okoro
<http://about.me/sunny.okoro?promo=email_sig>







<http://about.me/sunny.okoro?promo=email_sig>
  <http://about.me/sunny.okoro?promo=email_sig>

**Comment by lnu** [comment]
If you want to make changes on a repo you must do a [pull request](https://help.github.com/articles/using-pull-requests/).
But I guess your change will affect everyone who use the library. If you really need integer, fork the project.

**Comment by sunnyokoro** [comment]
This is a screen short of the generated db.



Yours
Sunday Okoro Awa
<http://about.me/sunny.okoro?promo=email_sig>Kno
*Know more about me*  about.me/sunny.okoro
<http://about.me/sunny.okoro?promo=email_sig>







<http://about.me/sunny.okoro?promo=email_sig>
  <http://about.me/sunny.okoro?promo=email_sig>

**Comment by HenryHatten** [comment]
sunnyokoro I'd like to see your changes. If you are going to do do either a pull request or a fork, great, if not, can you email them to me? Thanks...

**Comment by sunnyokoro** [comment]
I will fork it and make the changes there.

I will get back to you on that later today (11:13 AM over here).

**Comment by HenryHatten** [comment]
sunnyokoro did you do the fork yet? Thanks...

**Comment by AidanMcK** [comment]
I would be interested in a solution for this also if one is available.

**Comment by sunnyokoro** [comment]
Hi @all,
i have forked the project and committed the changes that will accommodate the integer data types.
check them out and see if it meets your needs.

Sorry I have not responded to you for a while, have been a bit busy on something.
Kindly Get back to me if you have any issues making use of it.

**Comment by sunnyokoro** [comment]
this is the link to the changes.
https://github.com/sunnyokoro/NHibernate.AspNet.Identity/tree/master/source

**Comment by lnu** [comment]
#26
