### ISSUE TITLE
Are you missing SaveUpdate in UserStore AddClaims,RemoveClaims?

### ISSUE THREAD

**Issue by Puresoft** [nhibernate/NHibernate.AspNet.Identity#50]
Also in Remove/Add Roles a call to Context.Update(user) is missing.

**Comment by alexi1982** [comment]
I have the same question.
Some update are missing or the specific methods are only called from inside an open session which save the user?

**Comment by lnu** [comment]
The code should be the same as the EF provider. Please provide a repro if you think there's an issue.
