### ISSUE TITLE
Problem IdentityConfig

### ISSUE THREAD

**Issue by Eluander** [nhibernate/NHibernate.AspNet.Identity#51]
In: Create ();

`var manager = new ApplicationUserManager(new UserStore<ApplicationUser>(**context.Get<ApplicationDbContext>()**));`

As removed ApplicationDbContext class, what should I spend?

**Comment by sunnyokoro** [comment]
Hi, I am not yet clear on your question. Please can you elaborate more?

**Comment by raphaeldiasrj** [comment]
I have this problem too.
@sunnyokoro, the static method Create of IdentityConfig.cs has the following line:
`var manager = new ApplicationUserManager(new UserStore<ApplicationUser>(context.Get<ApplicationDbContext>()));`

We deleted the ApplicationDbContext, obviously.
What can we code instead?

**Comment by lnu** [comment]
I did this [sample ](https://github.com/lnu/NHibernateIdentity)2 years ago. It uses unity to inject everything but you can replace it with what you want(we moved from unity to autofac).
