### ISSUE TITLE
Using NHibernate.AspNet.Identity with Identity Core

### ISSUE THREAD

**Issue by kidchenko** [nhibernate/NHibernate.AspNet.Identity#53]
The `NHibernate.AspNet.Identity` uses the old `AspNet.Identity`. 

Now in Asp .Net Core we have `AspNetCore.Identity`, there is any plans to support it?

**Comment by hazzik** [comment]
NHibernate does not support .NET Core, so there is no point to support it
from this library.

**Comment by kidchenko** [comment]
Hm, ok I understand it 👍

**Comment by dhughes55** [comment]
(see https://github.com/nhibernate/nhibernate.aspnet.identity/issues/63 for updated thread on same topic)
