### ISSUE TITLE
Compatibility with NHibernate 5.0.0

### ISSUE THREAD

**Issue by matteosaporiti** [nhibernate/NHibernate.AspNet.Identity#54]
It seems to me that the two are incompatible, it fails with:

> [MissingMethodException: Method not found: 'Void NHibernate.Mapping.ByCode.IComponentElementMapper`1.Property(System.Linq.Expressions.Expression`1<System.Func`2<!0,!!0>>)'.]
   NHibernate.AspNet.Identity.IdentityUserMap.<.ctor>b__8(IComponentElementMapper`1 comp) +0
   NHibernate.Mapping.ByCode.Impl.CustomizersImpl.PropertyContainerCustomizer`1.RegisterSetMapping(Action`1 collectionMapping, Action`1 mapping, MemberInfo[] members) +410
   NHibernate.AspNet.Identity.IdentityUserMap..ctor() +3421
[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck) +0
   System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark) +197
   System.Activator.CreateInstance() +132
   NHibernate.Mapping.ByCode.ModelMapper.AddMapping() +52
   NHibernate.AspNet.Identity.Helpers.MappingHelper.GetIdentityMappings(Type[] additionalTypes) +487

Given the fact that correctly supported Nhibernate 5 would require updating the solution to, at least, .NET 4.6.2 I would suggest to set the dependency on nuget to Nhibernate < 5.0.0 to prevent users from breaking their solution.

**Comment by hazzik** [comment]
NHibernate 5.0 is not binary compatible with the previous version.

**Comment by lnu** [comment]
@hazzik I'll check this.

**Comment by lnu** [comment]
Done https://github.com/nhibernate/NHibernate.AspNet.Identity/releases/tag/5.0.1
