### ISSUE TITLE
Error when get all users

### ISSUE THREAD

**Issue by cyrusd87** [nhibernate/NHibernate.AspNet.Identity#61]
Hi, 
there is the following error when I try to retrieve user informations

NHibernate.Exceptions.GenericADOException: Failed to execute multi query[SQL: select applicatio0_.applicationuser_key as Id6_0_, identityro2_.Id as Id9_1_, applicatio0_1_.AccessFailedCount as AccessFa2_6_0_, applicatio0_1_.Email as Email6_0_, applicatio0_1_.EmailConfirmed as EmailCon4_6_0_, applicatio0_1_.LockoutEnabled as LockoutE5_6_0_, applicatio0_1_.LockoutEndDateUtc as LockoutE6_6_0_, applicatio0_1_.PasswordHash as Password7_6_0_, applicatio0_1_.PhoneNumber as PhoneNum8_6_0_, applicatio0_1_.PhoneNumberConfirmed as PhoneNum9_6_0_, applicatio0_1_.TwoFactorEnabled as TwoFact10_6_0_, applicatio0_1_.UserName as UserName6_0_, applicatio0_1_.SecurityStamp as Securit12_6_0_, applicatio0_.Name as Name11_0_, applicatio0_.Surname as Surname11_0_, identityro2_.Name as Name9_1_, case when identityro2_1_.applicationrole_key is not null then 1 when identityro2_.Id is not null then 0 end as clazz_1_, roles1_.UserId as UserId0__, roles1_.RoleId as RoleId0__ from ApplicationUser applicatio0_ inner join AspNetUsers applicatio0_1_ on applicatio0_.applicationuser_key=applicatio0_1_.Id left outer join AspNetUserRoles roles1_ on applicatio0_.applicationuser_key=roles1_.UserId left outer join AspNetRoles identityro2_ on roles1_.RoleId=identityro2_.Id left outer join ApplicationRole identityro2_1_ on identityro2_.Id=identityro2_1_.applicationrole_key where upper(applicatio0_1_.UserName)=?;
↵select applicatio0_.applicationuser_key as Id6_0_, claims1_.Id as Id10_1_, applicatio0_1_.AccessFailedCount as AccessFa2_6_0_, applicatio0_1_.Email as Email6_0_, applicatio0_1_.EmailConfirmed as EmailCon4_6_0_, applicatio0_1_.LockoutEnabled as LockoutE5_6_0_, applicatio0_1_.LockoutEndDateUtc as LockoutE6_6_0_, applicatio0_1_.PasswordHash as Password7_6_0_, applicatio0_1_.PhoneNumber as PhoneNum8_6_0_, applicatio0_1_.PhoneNumberConfirmed as PhoneNum9_6_0_, applicatio0_1_.TwoFactorEnabled as TwoFact10_6_0_, applicatio0_1_.UserName as UserName6_0_, applicatio0_1_.SecurityStamp as Securit12_6_0_, applicatio0_.Name as Name11_0_, applicatio0_.Surname as Surname11_0_, claims1_.ClaimType as ClaimType10_1_, claims1_.ClaimValue as ClaimValue10_1_, claims1_.UserId as UserId10_1_, claims1_.UserId as UserId0__, claims1_.Id as Id0__ from ApplicationUser applicatio0_ inner join AspNetUsers applicatio0_1_ on applicatio0_.applicationuser_key=applicatio0_1_.Id left outer join AspNetUserClaims claims1_ on applicatio0_.applicationuser_key=claims1_.UserId where upper(applicatio0_1_.UserName)=?;
↵select applicatio0_.applicationuser_key as Id6_, applicatio0_1_.AccessFailedCount as AccessFa2_6_, applicatio0_1_.Email as Email6_, applicatio0_1_.EmailConfirmed as EmailCon4_6_, applicatio0_1_.LockoutEnabled as LockoutE5_6_, applicatio0_1_.LockoutEndDateUtc as LockoutE6_6_, applicatio0_1_.PasswordHash as Password7_6_, applicatio0_1_.PhoneNumber as PhoneNum8_6_, applicatio0_1_.PhoneNumberConfirmed as PhoneNum9_6_, applicatio0_1_.TwoFactorEnabled as TwoFact10_6_, applicatio0_1_.UserName as UserName6_, applicatio0_1_.SecurityStamp as Securit12_6_, applicatio0_.Name as Name11_, applicatio0_.Surname as Surname11_, logins1_.UserId as UserId0__, logins1_.LoginProvider as LoginPro2_0__, logins1_.ProviderKey as Provider3_0__ from ApplicationUser applicatio0_ inner join AspNetUsers applicatio0_1_ on applicatio0_.applicationuser_key=applicatio0_1_.Id left outer join AspNetUserLogins logins1_ on applicatio0_.applicationuser_key=logins1_.UserId where upper(applicatio0_1_.UserName)=?;
↵select applicatio0_.applicationuser_key as Id6_, applicatio0_1_.AccessFailedCount as AccessFa2_6_, applicatio0_1_.Email as Email6_, applicatio0_1_.EmailConfirmed as EmailCon4_6_, applicatio0_1_.LockoutEnabled as LockoutE5_6_, applicatio0_1_.LockoutEndDateUtc as LockoutE6_6_, applicatio0_1_.PasswordHash as Password7_6_, applicatio0_1_.PhoneNumber as PhoneNum8_6_, applicatio0_1_.PhoneNumberConfirmed as PhoneNum9_6_, applicatio0_1_.TwoFactorEnabled as TwoFact10_6_, applicatio0_1_.UserName as UserName6_, applicatio0_1_.SecurityStamp as Securit12_6_, applicatio0_.Name as Name11_, applicatio0_.Surname as Surname11_ from ApplicationUser applicatio0_ inner join AspNetUsers applicatio0_1_ on applicatio0_.applicationuser_key=applicatio0_1_.Id where upper(applicatio0_1_.UserName)=?;
↵] ---> System.InvalidOperationException: A Command è già associato un DataReader aperto, che deve essere chiuso.

**Comment by lnu** [comment]
Do you have any sample to reproduce the error?

**Comment by cyrusd87** [comment]
Hi @Inu the problem is happening when I try to make more calls togheter in a multithreading scenario... When  I try more requests in parallel I have this exception. How can I solve this?

**Comment by lnu** [comment]
Without a sample to reproduce the issue it's almost impossible to help you. What do you mean by multithreading? Is your session correctly configure?

**Comment by cyrusd87** [comment]
Hi @lnu ,

you can reproduce the issue if you simulte a multithreading scenario.
If you simulate more than 5 request concurrently you have the error.

**Comment by lnu** [comment]
How did you configure your session. Do you reuse the same session between different requests? The session is not thread safe.
