### ISSUE TITLE
 Invalid object name 'ApplicationUser'. 

### ISSUE THREAD

**Issue by samwood2011** [nhibernate/NHibernate.AspNet.Identity#62]
` var result = await SignInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, shouldLockout: false);` 

throws

 ` Invalid object name 'ApplicationUser'. `

```
 var myEntities = new[] {
                typeof(ApplicationUser)
            };
            string connectionString = "Data Source=XXXXXXXXXXX";

            var configuration = Fluently.Configure()
                .Database(MsSqlConfiguration.MsSql2008.ConnectionString(connectionString))
                .ExposeConfiguration(cfg =>
                {
                    cfg.AddDeserializedMapping(MappingHelper.GetIdentityMappings(myEntities), null);
                });

            var factory = configuration.BuildSessionFactory();
            var session = factory.OpenSession();

            var manager = new ApplicationUserManager(new UserStore<ApplicationUser>(session));
```

**Comment by samwood2011** [comment]
`NHibernate.Exceptions.GenericADOException: 'Failed to execute multi query[SQL: select applicatio0_.applicationuser_key as id1_30_0_, identityro2_.Id as id1_33_1_, applicatio0_1_.AccessFailedCount as acces2_30_0_, applicatio0_1_.Email as email3_30_0_, applicatio0_1_.EmailConfirmed as email4_30_0_, applicatio0_1_.LockoutEnabled as locko5_30_0_, applicatio0_1_.LockoutEndDateUtc as locko6_30_0_, applicatio0_1_.PasswordHash as passw7_30_0_, applicatio0_1_.PhoneNumber as phone8_30_0_, applicatio0_1_.PhoneNumberConfirmed as phone9_30_0_, applicatio0_1_.TwoFactorEnabled as twof10_30_0_, applicatio0_1_.UserName as user11_30_0_, applicatio0_1_.SecurityStamp as secu12_30_0_, identityro2_.Name as name2_33_1_, roles1_.UserId as useri1_31_0__, roles1_.RoleId as rolei2_31_0__ from ApplicationUser applicatio0_ inner join AspNetUsers applicatio0_1_ on applicatio0_.applicationuser_key=applicatio0_1_.Id left outer join AspNetUserRoles roles1_ on applicatio0_.applicationuser_key=roles1_.UserId left outer join AspNetRoles identityro2_ on roles1_.RoleId=identityro2_.Id where upper(applicatio0_1_.UserName)=?;
select applicatio0_.applicationuser_key as id1_30_0_, claims1_.Id as id1_34_1_, applicatio0_1_.AccessFailedCount as acces2_30_0_, applicatio0_1_.Email as email3_30_0_, applicatio0_1_.EmailConfirmed as email4_30_0_, applicatio0_1_.LockoutEnabled as locko5_30_0_, applicatio0_1_.LockoutEndDateUtc as locko6_30_0_, applicatio0_1_.PasswordHash as passw7_30_0_, applicatio0_1_.PhoneNumber as phone8_30_0_, applicatio0_1_.PhoneNumberConfirmed as phone9_30_0_, applicatio0_1_.TwoFactorEnabled as twof10_30_0_, applicatio0_1_.UserName as user11_30_0_, applicatio0_1_.SecurityStamp as secu12_30_0_, claims1_.ClaimType as claim2_34_1_, claims1_.ClaimValue as claim3_34_1_, claims1_.UserId as useri4_34_1_, claims1_.UserId as useri4_34_0__, claims1_.Id as id1_34_0__ from ApplicationUser applicatio0_ inner join AspNetUsers applicatio0_1_ on applicatio0_.applicationuser_key=applicatio0_1_.Id left outer join AspNetUserClaims claims1_ on applicatio0_.applicationuser_key=claims1_.UserId where upper(applicatio0_1_.UserName)=?;
select applicatio0_.applicationuser_key as id1_30_, applicatio0_1_.AccessFailedCount as acces2_30_, applicatio0_1_.Email as email3_30_, applicatio0_1_.EmailConfirmed as email4_30_, applicatio0_1_.LockoutEnabled as locko5_30_, applicatio0_1_.LockoutEndDateUtc as locko6_30_, applicatio0_1_.PasswordHash as passw7_30_, applicatio0_1_.PhoneNumber as phone8_30_, applicatio0_1_.PhoneNumberConfirmed as phone9_30_, applicatio0_1_.TwoFactorEnabled as twof10_30_, applicatio0_1_.UserName as user11_30_, applicatio0_1_.SecurityStamp as secu12_30_, logins1_.UserId as useri1_32_0__, logins1_.LoginProvider as login2_32_0__, logins1_.ProviderKey as provi3_32_0__ from ApplicationUser applicatio0_ inner join AspNetUsers applicatio0_1_ on applicatio0_.applicationuser_key=applicatio0_1_.Id left outer join AspNetUserLogins logins1_ on applicatio0_.applicationuser_key=logins1_.UserId where upper(applicatio0_1_.UserName)=?;
select applicatio0_.applicationuser_key as id1_30_, applicatio0_1_.AccessFailedCount as acces2_30_, applicatio0_1_.Email as email3_30_, applicatio0_1_.EmailConfirmed as email4_30_, applicatio0_1_.LockoutEnabled as locko5_30_, applicatio0_1_.LockoutEndDateUtc as locko6_30_, applicatio0_1_.PasswordHash as passw7_30_, applicatio0_1_.PhoneNumber as phone8_30_, applicatio0_1_.PhoneNumberConfirmed as phone9_30_, applicatio0_1_.TwoFactorEnabled as twof10_30_, applicatio0_1_.UserName as user11_30_, applicatio0_1_.SecurityStamp as secu12_30_ from ApplicationUser applicatio0_ inner join AspNetUsers applicatio0_1_ on applicatio0_.applicationuser_key=applicatio0_1_.Id where upper(applicatio0_1_.UserName)=?;
]'`

**Comment by juliocgs** [comment]
I'm having the same issue. Anyone has a clue on this?

**Comment by juliocgs** [comment]
Solved the problem by creating ApplicationUse table on database as below:

`
CREATE TABLE ApplicationUser(
	applicationuser_key NVARCHAR(128) PRIMARY KEY
)

ALTER TABLE ApplicationUser WITH CHECK ADD CONSTRAINT [FK_ApplicationUser_AspNetUsers] FOREIGN KEY(applicationuser_key)
REFERENCES AspNetUsers (Id)
`

After this everything seems normal.

The thing is: I do not know why this table is needed.

**Comment by juliocgs** [comment]
`aa`

**Comment by lnu** [comment]
There are always two tables for the users: aspnetuser and one with the name of your application user class, in this case ApplicationUser. How did you create your schema? You should create it with the script generated by the ScriptGenerator from NHibernate. If you try the sample provided, you'll see what are the generated tables.

```
 // this NHibernate tool takes a configuration (with mapping info in)
 // and exports a database schema from it
 new SchemaExport(_configuration)
                .SetOutputFile(path)
                .Create(true, true /* DROP AND CREATE SCHEMA */);
```

**Comment by juliocgs** [comment]
> How did you create your schema?
I created a MVC5 Application from scratch and had EF create it for me. This way ApplicationUser table was not created.

> If you try the sample provided, you'll see what are the generated tables.
I'll give it a try.

Thanks

**Comment by juliocgs** [comment]
I created an empty database and ran SchemaExport on it. All tables where created normally, incluing ApplicationUser.
Everything seems to work as intended with this schema.

The only point I miss is why ApplicationUser table is needed when EF native implementation does not use it. I really don't mind the table, I just want to know why.

**Comment by lnu** [comment]
The `ApplictionUser` object is used to store extra properties. All extra properties will be added to the corresponding `ApplicationUser` table. It's [table per subclass](http://nhibernate.info/doc/nhibernate-reference/inheritance.html) mapping. If you don't need extra properties you can directly use `IdentityUser` I think.

**Comment by juliocgs** [comment]
I see, I'm really grateful.
Thanks for the help =]
